# Generated by Django 3.0.6 on 2020-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('E6', 'E6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3')], max_length=2)),
                ('test_type', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('average', models.CharField(max_length=10)),
                ('std_dev', models.CharField(max_length=20)),
                ('cand_num', models.CharField(max_length=20)),
                ('additional_info', models.TextField()),
                ('student', models.ManyToManyField(default=None, to='students.Student')),
            ],
        ),
    ]
