# Generated by Django 3.0.6 on 2020-06-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('grade', models.CharField(choices=[('초1', '초1'), ('초2', '초2'), ('초3', '초3'), ('초4', '초4'), ('초5', '초5'), ('초6', '초6'), ('중1', '중1'), ('중2', '중2'), ('중3', '중3'), ('고1', '고1'), ('고2', '고2'), ('고3', '고3')], max_length=2)),
                ('test_type', models.CharField(choices=[('1학기 중간', '1학기 중간'), ('1학기 기말', '1학기 기말'), ('2학기 중간', '2학기 중간'), ('2학기 기말', '2학기 기말'), ('3월 모의고사', '3월 모의고사'), ('6월 모의고사', '6월 모의고사'), ('9월 모의고사', '9월 모의고사'), ('11월 모의고사', '11월 모의고사')], max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('average', models.CharField(max_length=10)),
                ('std_dev', models.CharField(max_length=20)),
                ('cand_num', models.CharField(max_length=20)),
                ('additional_info', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(default=None, to='students.Student')),
            ],
        ),
    ]
