# Generated by Django 3.0.6 on 2020-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_auto_20200519_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('grade', models.CharField(choices=[('초1', '초1'), ('초2', '초2'), ('초3', '초3'), ('초4', '초4'), ('초5', '초5'), ('초6', '초6'), ('중1', '중1'), ('중2', '중2'), ('중3', '중3'), ('고1', '고1'), ('고2', '고2'), ('고3', '고3')], max_length=2)),
                ('group', models.ManyToManyField(default=None, to='groups.Group')),
            ],
        ),
    ]
